# Book settings
title: My sample book
author: The Jupyter Book Community
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex
    
launch_buttons:
  notebook_interface : "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url      : "http://ac4fa73f328ee4022bd1e5cbeadcba2b-1718238252.ca-central-1.elb.amazonaws.com/"
  thebe              : true

repository:
  url          : https://github.com/TomasBeuzen/jupiter-book  # The URL to your book's repository
  path_to_book : ""  # A path to your book's folder, relative to the repository root.
  branch       : master  # Which branch of the repository should be used when creating links

sphinx:
  extra_extensions:
    - sphinx_thebe
